version: "3.9"

services:

  booksphere-app:

    build: .

    container_name: booksphere-app

    ports:
      - "5000:5000"

    volumes:
      - .:/app

    environment:
      DATABASE_URL: postgresql://booksphere_user:booksphere_password@postgres-db:5432/booksphere_db

    depends_on:
      - postgres-db

    restart: unless-stopped


  postgres-db:

    image: postgres:15

    container_name: booksphere-postgres

    environment:
      POSTGRES_USER: booksphere_user
      POSTGRES_PASSWORD: booksphere_password
      POSTGRES_DB: booksphere_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped


volumes:
  postgres_data: