apiVersion: v1
kind: Service

metadata:
  name: booksphere-service
  namespace: booksphere

spec:
  selector:
    app: booksphere

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: LoadBalancer